// Import global CSS styles
import './globals.css';

// Import necessary types and components from Next.js
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar'; // Import the Navbar component from the specified path

// Load the Inter font with the specified subsets
const inter = Inter({ subsets: ['latin'] });

// Define metadata for the webpage
export const metadata: Metadata = {
  title: 'Create Next App', // Title of the webpage
  description: 'Generated by create next app', // Description of the webpage
}

// Define the RootLayout component which acts as a base layout for the entire application
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en"> {/* Set the language attribute of the HTML */}
      <body className={inter.className}> {/* Apply the Inter font to the body */}
        <Navbar /> {/* Render the Navbar component */}
        {children} {/* Render the content passed as children */}
      </body>
    </html>
  );
}
